const javas = () => {
    function verifyPassword() {  
        var pw = document.getElementById("pswd").value;  
        //check empty password field  
        if(pw == "" ) {  
           document.getElementById("message").innerHTML = "**Fill the password please!";  
           return false;  
        }  

    return (  
        <div>
            <h1>hi</h1>
        </div>
    );
}
}
 
export default javas;